// facial-recognition-demo/src/app/add/add.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { ContentService } from '../content.service';
import { FormGroup, FormControl } from '@angular/forms'

@Component({
  selector: 'app-add',
  templateUrl: './add.component.html',
  styleUrls: ['./add.component.css']
})
export class AddComponent implements OnInit {

  page: Object;

  formdata = new FormGroup({
    firstname: new FormControl(),
    lastname: new FormControl(),
    bbdID: new FormControl(),
    position: new FormControl()
  });

  firstname;
  lastname;
  bbdID;
  position;


  constructor(private contentService: ContentService) { }

  ngOnInit() {
    this.page = this.contentService.pages['add'];
  }

  onClickSubmit(data) {
    this.firstname = data.firstname;
    this.lastname = data.lastname;
    this.bbdID = data.bbdID;
    this.position = data.position;

    console.log("New user:");
    console.log("First Name:" + this.firstname);
    console.log("Last Name:" + this.lastname);
    console.log("bbdID:" + this.bbdID);
    console.log("Position:" + this.position);
  }
  // width = 320;    // We will scale the photo width to this
  // height = 0;     // This will be computed based on the input stream

  // streaming = false;

  // video = null;
  // canvas = null;
  // photo = null;
  // startbutton = null;

  // startup() {
  //   this.video = document.getElementById('video');
  //   this.canvas = document.getElementById('canvas');
  //   this.photo = document.getElementById('photo');
  //   this.startbutton = document.getElementById('startbutton');
  //   navigator.mediaDevices.getUserMedia({ video: true, audio: false })
  //     .then(function (stream) {
  //       this.video.srcObject = stream;
  //       this.video.play();
  //     })
  //     .catch(function (err) {
  //       console.log("An error occurred! " + err);
  //     });
  //   // function() {
  //   //   var width = 320;    // We will scale the photo width to this
  //   //   var height = 0;     // This will be computed based on the input stream

  //   //   var streaming = false;

  //   //   var video = null;
  //   //   var canvas = null;
  //   //   var photo = null;
  //   //   var startbutton = null;
  //   // }
  //   this.video.addEventListener('canplay', function(ev){
  //     if (!this.streaming) {
  //       this.height = this.video.videoHeight / (this.video.videoWidth/this.width);
      
  //       this.video.setAttribute('width', this.width);
  //       this.video.setAttribute('height', this.height);
  //       this.canvas.setAttribute('width', this.width);
  //       this.canvas.setAttribute('height', this.height);
  //       this.streaming = true;
  //     }
  //   }, false);

  //   this.startbutton.addEventListener('click', function(ev){
  //     this.takepicture();
  //     ev.preventDefault();
  //   }, false);
  // }
  

  // takepicture() {
  //   var context = this.canvas.getContext('2d');
  //   if (this.width && this.height) {
  //     this.canvas.width = this.width;
  //     this.canvas.height = this.height;
  //     context.drawImage(this.video, 0, 0, this.width, this.height);
    
  //     var data = this.canvas.toDataURL('image/png');
  //     this.photo.setAttribute('src', data);
  //   } else {
  //     this.clearphoto();
  //   }
  // }

  // clearphoto() {
  //   var context = this.canvas.getContext('2d');
  //   context.fillStyle = "#AAA";
  //   context.fillRect(0, 0, this.canvas.width, this.canvas.height);

  //   var data = this.canvas.toDataURL('image/png');
  //   this.photo.setAttribute('src', data);
  // }
  
}


<div class="content">
  <h2>Add New User</h2>
  <form [formGroup]="formdata" (ngSubmit)="onClickSubmit(formdata.value)">
    <div id="userInfo">
      <div class="container">
        <p>Please fill in this form to create an account.</p>
        <hr>

        <label for="firstname"><b>First Name</b></label>
        <input type="text" placeholder="Enter First Name" formControlName="firstname" required>

        <label for="lastname"><b>Last Name</b></label>
        <input type="text" placeholder="Enter Last Name" formControlName="lastname" required>

        <label for="bbdID"><b>User Domain</b></label>
        <input type="text" placeholder="Enter User Domain (bbdnet...)" formControlName="bbdID" required>

        <label for="position"><b>Position</b></label>
        <input type="text" placeholder="Enter Employee Position" formControlName="position" required>

      </div>
    </div>
    <div id="photoInput">
      <!-- <div class="camera">
        <video id="video">Video stream not available.</video>
        <button id="startbutton">Take photo</button>
      </div>
      <canvas id="canvas">
        </canvas>
        <div class="output">
          <img id="photo" alt="The screen capture will appear in this box.">
        </div>
    </div> -->
    <hr>
    <button type="submit" class="registerbtn">Register</button>
    <hr>
  </form>
</div>

// react_facial_react/src/views/Add.js
import React, { Component } from "react";
import { HelpBlock, ButtonGroup, ButtonToolbar, Button, FormGroup, FormControl, ControlLabel } from "react-bootstrap";
import "./Add.css";
import VideoInput from './VideoInput';

export default class Add extends Component {
    constructor(props) {
        super(props);
        this.state = {
            firstname: null,
            lastname: null,
            bbdID: null,
            position: null,
            face_front: null,
            face_left: null,
            face_right: null
        }
    }

    handleChange = event => {
        this.setState({
            [event.target.id]: event.target.value
        });
    }

    render() {
        return (
            <div className="content">
                <h2>Add New User</h2>
                <form>
                    <div id="userInfo">
                        <div className="container">
                            <FormGroup controlId="firstname" bsSize="large">
                                <ControlLabel>First Name</ControlLabel>
                                <FormControl
                                    autoFocus
                                    type="text"
                                    placeholder="Enter First Name"
                                    defaultValue={this.state.firstname}
                                    onChange={this.handleChange}
                                />
                            </FormGroup>

                            <FormGroup controlId="lastname" bsSize="large">
                                <ControlLabel>Surname</ControlLabel>
                                <FormControl
                                    autoFocus
                                    type="text"
                                    placeholder="Enter Last Name"
                                    defaultValue={this.state.lastname}
                                    onChange={this.handleChange}
                                />
                            </FormGroup>

                            <FormGroup controlId="bbdID" bsSize="large">
                                <ControlLabel>User Domain</ControlLabel>
                                <FormControl
                                    autoFocus
                                    type="text"
                                    placeholder="Enter User Domain (bbdnet...)"
                                    defaultValue={this.state.bbdID}
                                    onChange={this.handleChange}
                                />
                            </FormGroup>

                            <FormGroup controlId="position" bsSize="large">
                                <ControlLabel>position</ControlLabel>
                                <FormControl
                                    autoFocus
                                    type="text"
                                    placeholder="Enter Employee Position"
                                    defaultValue={this.state.position}
                                    onChange={this.handleChange}
                                />
                            </FormGroup>
                        </div>
                    </div>
                    <div id="photoInput">
                    </div>
                    <hr />

                    <ButtonToolbar>
                        <ButtonGroup>
                            <Button
                                bsSize="large"
                                // disabled={!this.validateForm()}
                                onClick={this.saveAndContinue}
                            >
                                Save &amp; Continue
                            </Button>
                        </ButtonGroup>
                    </ButtonToolbar>
                    <hr />
                    {/* <form [formGroup]="formdata" (ngSubmit)="onClickSubmit(formdata.value)"> */}
                    {/* <div id="userInfo">
                        <div className="container">
                            <p>Please fill in this form to create an account.</p>
                            <hr />

                            <label for="firstname"><b>First Name</b></label>
                            <input type="text" placeholder="Enter First Name" formControlName="firstname" required />

                            <label for="lastname"><b>Last Name</b></label>
                            <input type="text" placeholder="Enter Last Name" formControlName="lastname" required />

                            <label for="bbdID"><b>User Domain</b></label>
                            <input type="text" placeholder="Enter User Domain (bbdnet...)" formControlName="bbdID" required />

                            <label for="position"><b>Position</b></label>
                            <input type="text" placeholder="Enter Employee Position" formControlName="position" required />

                        </div>
                    </div>
                    <div id="photoInput">
                    </div> */}
                    {/* <button type="submit" className="registerbtn">Register</button> */}
                </form>
            </div>
        );
    }
}
